[package]
name = "spdlog"
version = "0.1.0"
edition = "2023"
authors = []

[module]
name = "com.github.cmod_ecosystem.spdlog"
root = "src/lib.cppm"

[dependencies]
"github.com/cmod-ecosystem/fmt" = "*"

[dev-dependencies]

[build-dependencies]

[features]

[compat]
cpp = ">=20"
platforms = []

[toolchain]
compiler = "clang"
cxx_standard = "20"

[build]
type = "static-lib"
parallel = true
incremental = true
include_dirs = []
extra_flags = ["-fno-exceptions"]
sources = []
exclude = []

[target]

# ==========================================================
# TODO: Manual dependency mapping needed
# ==========================================================
# find_package(Threads) -> add Git URL to [dependencies]
# Linked libraries: Threads::Threads, Threads::Threads, fmt::fmt-header-only, fmt::fmt-header-only, fmt::fmt, fmt::fmt, log, log
