//===-- llvm-config.h - Minimal stub for standalone Demangle build --------===//
//
// This is a minimal stub of llvm/Config/llvm-config.h providing only the
// macros needed by DemangleConfig.h. In a full LLVM build, this file is
// generated by CMake.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_CONFIG_H
#define LLVM_CONFIG_H

// Build as a static library — no dllexport/dllimport decorations needed.
#ifndef LLVM_BUILD_STATIC
#define LLVM_BUILD_STATIC
#endif

#endif
