[package]
name = "roller"
version = "0.1.0"

[module]
name = "local.roller"
root = "src/lib.cppm"

[dependencies]
dice = { path = "../dice" }

[toolchain]
compiler = "clang"
cxx_standard = "20"

[build]
type = "binary"
